name: services_form
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  build_runner: ^1.0.0
  json_serializable: ^3.2.2
  auto_size_text: ^2.1.0
  lottie: 0.7.0+1
  sizer: ^1.1.8
  esc_pos_bluetooth: ^0.2.8
  flutter_bluetooth_basic: 0.1.5
  image: ^2.1.4
  double_back_to_close: ^1.0.2+mit
  firebase_database:
  cloud_firestore: ^1.0.3
  firebase_core: ^1.0.2
  native_contact_picker: ^0.0.6
  avatar_letter: ^1.0.1
  url_launcher:
  intl: 
  flutter_slidable:
  flutter_typeahead: ^3.1.0
  adaptive_theme: ^1.1.0
  oktoast: ^3.0.0
  flutter_fluid_slider: ^1.0.3
  percent_indicator: ^2.1.9+1
  dismissible_page: ^0.6.1
  dropdown_formfield: ^0.1.3
  jiffy: ^4.0.0
  vibration: ^1.7.3
  flutter_full_pdf_viewer: ^1.0.6
  path_provider: ^0.5.0
  provider: ^5.0.0
  pinput: ^1.2.0
  sqflite:
  after_layout: ^1.1.0
  firebase_storage: ^8.0.1
  pdf:
  share: ^2.0.1
  pull_to_refresh: ^1.6.4
  settings_ui: ^0.6.0
  flutter_native_splash: 0.3.0
  shared_preferences: ^0.5.0
  file_picker: ^1.3.6
  local_auth:
  assets_audio_player:
  firebase_auth: ^1.0.1
  quick_actions: ^0.6.0
  modal_progress_hud: ^0.1.3

flutter_native_splash:
  color: "#ffffff"
  image: "assets/logoBlack.png"
  color_dark: "#1a1a1a"
  image_dark: "assets/logo.png"
  android: true
  ios: true


dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - lottie/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
